Repository OWASP/www-project-machine-learning-security-top-10, pull requests merged in 2023-07, with the labels that each got.

#8 Fix wrong link in top10 markdown file
  2023/ML04_2023-Membership_Inference_Attack.md
  2023/Top_10.md
Labels: fix-typo

#18 modify CODEOWNERS to members with write access
  .github/CODEOWNERS
Labels: fix/typo, issues/admin

#20 add feedback report and pull request templates
  .github/ISSUE_TEMPLATE/feedback-report.yaml
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: issues/admin

#22 shsingh/update README
  README.md
Labels: documentation, issues/admin

#31 Issue #29: Create a RELATED.md to list similar projects and SIGs
  RELATED.md
Labels: documentation

#35 add: fix website
  CHARTER.md
  RELATED.md
  leaders.md
Labels: documentation, issues/admin

#37 shsingh/fix-website
  tab_charter.md
  tab_related.md
Labels: fix/typo, issues/admin
